### ISSUE TITLE
Error after Sign in

### ISSUE THREAD

**Issue by alexisleroy** [Tito1337/domo-cloud#1]
Une idée du problème ? L'erreur apparait après enregistrement 'Sign in'

![screen shot 2016-04-14 at 11 59 21](https://cloud.githubusercontent.com/assets/5815536/14524530/2144101c-0239-11e6-9860-697ee6784412.png)

**Comment by Tito1337** [comment]
Tu as modifié index.php ?

L'erreur dit que y'a déjà eu du contenu de page envoyé au navigateur en fait, ce qui pose problème parce que plus tard on essaye de créer des cookies, et ça ne peut être fait que dans les headers HTTP donc impossible après du contenu de page.
